services:
  telemetry-lab:
    image: wvxbs/telemetry-lab:latest
    build:
      context: .
    container_name: telemetry-lab
    ports:
      - "8501:8501"
    volumes:
      - /mnt/c/Users/gabri/OneDrive/Documents/tools:/data/reports:ro
      - /mnt/c/Users/gabri/OneDrive/Documents/tools/telemetry-lab-data/benchmarks:/data/benchmarks:rw
    restart: unless-stopped
