services:
  telemetry-lab:
    image: wvxbs/telemetry-lab:latest
    build:
      context: .
    container_name: telemetry-lab
    ports:
      - "8501:8501"
    volumes:
      - /mnt/c/Users/gabri/OneDrive/Documents/tools/Desmerdíficar o windows/relatório de sensores/cinebench 2026:/data/cinebench-2026:ro
    restart: unless-stopped
